name: Advanced Metrics
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: bibek1414
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kathmandu
          plugin_languages: yes
          plugin_achievements: yes
