name: Metrics
on:
  schedule: 
    - cron: "0 */12 * * *"  
  workflow_dispatch:
  push: 
    branches: ["master", "main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: bibek1414
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kathmandu
          
          # Plugins
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          
          plugin_followup: yes
          plugin_followup_sections: repositories
          
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
          
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          
          plugin_discussions: yes
          plugin_discussions_categories: yes
          
          plugin_topics: yes
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          plugin_topics_limit: 15
          
          plugin_code: yes
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public
          
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_days: 14
          plugin_activity_visibility: all
          plugin_activity_timestamps: yes
          
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed
          plugin_achievements_limit: 0
          
          # WakaTime Plugin (Added)
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_limit: 5
